# Generated by Django 4.2.3 on 2023-07-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='retingAuthor',
            new_name='ratingAuthor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='reting',
            new_name='rating',
        ),
    ]
