# Generated by Django 4.2.3 on 2023-07-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_rename_retingauthor_author_ratingauthor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reting',
            new_name='rating',
        ),
    ]
